#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Pouch\Pouch;
use Dicker\Commands;
use Symfony\Component\Finder\Finder;
use Symfony\Component\Console\Application;

Pouch::bootstrap(__DIR__);

pouch()->bind('stubsFinder', function () {
    return (new Finder())->in(__DIR__.'/stubs')->name('*.stub')->ignoreDotFiles(false);
});

$application = new Application('Dicker CLI');

$application->add(new Commands\InitCommand);
$application->add(new Commands\SwitchWebserverCommand);
$application->add(new Commands\SwitchCacheCommand);
$application->add(new Commands\SwitchPhpCommand);
$application->add(new Commands\ExtensionEnableCommand);

$application->run();
