#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Dicker\Commands\InitCommand;
use Symfony\Component\Console\Application;

$application = new Application('Dicker CLI');

$application->add(new InitCommand);

$application->run();
