#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Dicker\Commands;
use Symfony\Component\Console\Application;

$application = new Application('Dicker CLI');

$application->add(new Commands\InitCommand);
$application->add(new Commands\SwitchPhpCommand());
$application->add(new Commands\SwitchWebserverCommand);

$application->run();
