#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Dockr\Commands;
use Symfony\Component\Console\Application;

$application = new Application('Dockr CLI 1.0');

$application->add(new Commands\InitCommand);
$application->add(new Commands\SwitchWebserverCommand);
$application->add(new Commands\SwitchCacheCommand);
$application->add(new Commands\SwitchPhpCommand);
$application->add(new Commands\ExtensionEnableCommand);
$application->add(new Commands\ExtensionDisableCommand);

$application->run();
