#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Dockr\Commands;
use Symfony\Component\Console\Application;

$application = new Application('Dockr CLI 1.0');

$application->add(new Commands\InitCommand);
$application->add(new Commands\SwitchWebServerCommand);
$application->add(new Commands\SwitchCacheStoreCommand);
$application->add(new Commands\SwitchPhpVersionCommand);
$application->add(new Commands\ExtensionEnableCommand);
$application->add(new Commands\ExtensionDisableCommand);

$application->run();
